# Generated by Django 5.0.2 on 2024-04-05 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Document', 'Document'), ('Colis', 'Colis')], max_length=100, verbose_name='Genre')),
                ('longueur', models.IntegerField()),
                ('largeur', models.IntegerField()),
                ('hauteur', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('poids', models.IntegerField()),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Destinataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prenom')),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateExp', models.DateField()),
                ('pays_origine', models.CharField(max_length=100, verbose_name='Pays_Origine')),
                ('ville_origin', models.CharField(max_length=100, verbose_name='Ville_Origine')),
                ('pays_destination', models.CharField(max_length=100, verbose_name='Pays_Destination')),
                ('ville_destination', models.CharField(max_length=100, verbose_name='Ville_Destination')),
                ('mode_transport', models.CharField(choices=[('Terrestre', 'Terrestre'), ('Aerien', 'Aerien'), ('Maritime', 'Maritime')], max_length=50, verbose_name='Mode_Transport')),
                ('moyen_paiement', models.CharField(choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard')], max_length=50)),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colis.colis')),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise', models.CharField(choices=[('XAF', 'XAF'), ('Euro', 'Euro'), ('Dollars', 'Dollars')], max_length=100, verbose_name='Devise')),
                ('valeur', models.FloatField(null=True)),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colis.colis')),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colis.expedition')),
            ],
        ),
    ]
