# Generated by Django 5.0.2 on 2024-04-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0002_remove_devis_colis_remove_expedition_colis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='dateExp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='devis',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='devis',
            name='hauteur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devis',
            name='largeur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devis',
            name='longueur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devis',
            name='poids',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devis',
            name='quantite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devis',
            name='valeur',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='dateExp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='hauteur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='largeur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='longueur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='poids',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='quantite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
