# Generated by Django 5.0.2 on 2024-04-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0004_remove_expedition_moyen_paiement_expedition_devise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='expedition',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='valeur',
        ),
    ]
