# Generated by Django 5.0.2 on 2024-04-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0005_remove_devis_expedition_remove_devis_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='nom',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
